require 'dotenv'
require 'httparty'

require_relative 'semantics/api_error'
require_relative 'semantics/api_misssing_token_error'
require_relative 'semantics/ax_data'
require_relative 'semantics/configuration'
require_relative 'semantics/content_project'
require_relative 'semantics/login'
require_relative 'semantics/thing'
